name: Build and Deploy Sphinx Docs to GitHub Wiki

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
        pip install sphinx-markdown-builder

    - name: Build the documentation
      run: |
        cd docs
        make markdown

    - name: Push to Wiki
      run: |
        cd docs
        git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/brian-frost-1/test-sphinx.wiki.git wiki
        cp -r build/markdown/index.md wiki/Home.md
        cd wiki
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Update Wiki with latest Sphinx documentation"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/brian-frost-1/test-sphinx.wiki.git
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
